import Head from 'next/head'
import { Box, Checkbox, CheckboxGroup, Input } from '@chakra-ui/react'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import { DeleteIcon } from '@chakra-ui/icons'
export default function Home() {
  return (
    <>
      <Head>
        <title>TODO App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <h1>TODO</h1>
        <div className='task-container'>
          <Checkbox size='md' colorScheme='blue' className='checkbox'>Checkbox</Checkbox>
          <DeleteIcon color="red"/>
        </div>
		
        
        <Input className='text-input' placeholder='Write a task' />
      </main>
    </>
  )
}
